[project]
name = "store-sales-forecasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasetsforecast>=1.0.1",
    "jupyter>=1.1.1",
    "jupyterlab-vim>=4.1.4",
    "kaggle>=1.7.4.5",
    "kagglehub>=1.0.2",
    "lab>=8.10",
    "matplotlib>=3.10.9",
    "neuralforecast>=3.1.9",
    "numba>=0.66.0",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "polars>=1.42.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "statsforecast>=2.0.2",
    "statsmodels>=0.14.6",
]
